export * from './GenresPage/GenresPage'
export * from './MoviesPage/MoviesPage'
export * from './MovieInfoPage/MovieInfoPage'
export * from './GenresPage/MoviesByGenrePage/MoviesByGenrePage'
export * from './MainPage/MainPage'